[platformio]
default_envs = pico32

[env:pico32]
platform = espressif32@6.8.1
board = pico32
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200

platform_packages =
    framework-arduinoespressif32@3.20017.0
    toolchain-xtensa-esp32@8.4.0+2021r2-patch5
    tool-esptoolpy@1.40501.0

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17

lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.11
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.5
