name: CalmNest PICO D4 Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio==6.1.18

      - name: Show PlatformIO Version
        run: pio --version

      - name: Clean Project
        run: pio run -t clean

      - name: Compile ESP32 PICO D4
        run: pio run -e pico32
